### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by trollkotze** [grzegorznowak/ansible-nvm-node#3]
I installed ansible and did `ansible-galaxy install grzegorznowak.nvm_node`.
So how do I run nvm or node now?

**Comment by grzegorznowak** [comment]
Hey buddy,

you need to run it via a Ansible playbook. The ansible-galaxy installation is like fetching sources, you still need to compile the role onto a server of your choosing; including `localhost`. 
Hope that analogy make sense!

Refer to the `Example playbook` section in the README.
