### ISSUE TITLE
Bash always opens in home directory

### ISSUE THREAD

**Issue by etlam** [grzegorznowak/ansible-nvm-node#4]
After installing this role every bash starts in your home directory.  
Even if you click `Open this folder in terminal` in Nautilus it always jumps to the home directory.
I will provide a pull request ;-)

**Comment by grzegorznowak** [comment]
Hey @etlam. I've never really tested nor used that role on my host directly, so didn't notice that. It was meant to be installed on containers/vm as I saw it. So thanks for that new angle! Will run your PR through molecule test suite and merge it if all's fine. 

Still gotta setup automations in this repo. 
Now repeat that 100 times: 
"Still gotta...".

**Comment by etlam** [comment]
Could you please do a release, so the fix also becomes available on [Ansible Galaxy](https://galaxy.ansible.com/grzegorznowak/nvm_node).
Thanks for the great work!

**Comment by grzegorznowak** [comment]
done, thanks for the reminder!
